import '../styles/core-lab-tools.css';

type Telemetry=Record<string,string|number>;type Inventory={meshes:Array<{id:string;name:string;materials:string[];visible:boolean}>};
const root=document.querySelector<HTMLElement>('[data-core-lab]');
if(root){
  const tools=root.querySelector<HTMLElement>('[data-inspector-section="console"]'),stage=root.querySelector<HTMLElement>('[data-core-drop]');
  if(tools){
    tools.querySelector('.tools-note')?.remove();
    tools.insertAdjacentHTML('beforeend',`<div class="tools-grid"><article><small>ANALYZE</small><b>ASSET AUDIT</b><span data-tool-audit>LOAD A MODEL TO RUN AUDIT</span></article><article><small>BUDGET</small><b>PERFORMANCE</b><span data-tool-performance>WAITING FOR TELEMETRY</span></article></div><div class="tools-section"><b>VIEW HELPERS</b><span>Inspect geometry without modifying the source asset.</span><div class="tools-actions helpers"><button type="button" data-tool="wireframe">WIREFRAME</button><button type="button" data-tool="box">BOUNDING BOX</button><button type="button" data-tool="axes">AXES</button><button type="button" data-tool="grid">GRID</button><button type="button" data-tool="normals">NORMALS</button><button type="button" data-tool="skeleton">SKELETON</button></div><div class="tools-actions utility"><button type="button" data-tool="refit">CENTER / REFIT</button><button type="button" data-tool="snapshot">SNAPSHOT PNG</button></div></div><div class="tools-section"><div class="tools-heading"><div><b>ASSET VALIDATION</b><span>Integration guidance based on practical web budgets; informational notes are not failures.</span></div></div><div class="validation-list" data-validation><span class="inventory-empty">LOAD A MODEL TO VALIDATE</span></div></div><div class="tools-section"><div class="tools-heading"><div><b>MESH / MATERIAL INSPECTOR</b><span>Hide individual meshes to inspect the asset structure and material assignment.</span></div><div><button type="button" data-hide-all>HIDE ALL</button><button type="button" data-show-all>SHOW ALL</button></div></div><div class="mesh-inventory" data-mesh-inventory><span class="inventory-empty">LOAD A MODEL TO INSPECT MESHES</span></div></div><div class="tools-section"><b>HANDOFF</b><span>Keep the current lab state for integration or review.</span><div class="tools-actions"><button type="button" data-tool="copy">COPY CONFIG</button><button type="button" data-tool="export">EXPORT REPORT</button></div><div class="tool-feedback" data-tool-feedback>READY</div></div>`);
    const audit=tools.querySelector<HTMLElement>('[data-tool-audit]'),performance=tools.querySelector<HTMLElement>('[data-tool-performance]'),feedback=tools.querySelector<HTMLElement>('[data-tool-feedback]'),inventory=tools.querySelector<HTMLElement>('[data-mesh-inventory]'),validation=tools.querySelector<HTMLElement>('[data-validation]');let telemetry:Telemetry={},currentInventory:Inventory={meshes:[]};
    const getConfig=()=>({generatedAt:new Date().toISOString(),asset:telemetry,transform:Object.fromEntries([...root.querySelectorAll<HTMLInputElement>('[data-transform]')].map(input=>[`${input.dataset.transform}.${input.dataset.axis}`,Number(input.value)])),render:Object.fromEntries([...root.querySelectorAll<HTMLInputElement>('[data-render]')].map(input=>[input.dataset.render??'value',Number(input.value)])),lighting:{colors:Object.fromEntries([...root.querySelectorAll<HTMLInputElement>('[data-light-color]')].map(input=>[input.dataset.lightColor??'light',input.value])),intensity:Object.fromEntries([...root.querySelectorAll<HTMLInputElement>('[data-light-intensity]')].map(input=>[input.dataset.lightIntensity??'light',Number(input.value)]))}});const tell=(message:string)=>{if(feedback)feedback.textContent=message;root.dispatchEvent(new CustomEvent('corelab:log',{detail:{es:`Tools · ${message}`,en:`Tools · ${message}`}}))};
    const validate=(data:Telemetry)=>{if(!validation)return;const warnings:string[]=[],info:string[]=[];const tri=Number(data.triangles||0),verts=Number(data.vertices||0),mats=Number(data.materials||0),meshes=Number(data.meshes||0),anim=Number(data.animations||0);if(tri>150000)warnings.push(`HIGH TRIANGLE COUNT · ${tri.toLocaleString()} · GUIDANCE`);if(verts>200000)warnings.push(`HIGH VERTEX COUNT · ${verts.toLocaleString()} · GUIDANCE`);if(mats>30)warnings.push(`MANY MATERIALS · ${mats} · GUIDANCE`);if(meshes>80)warnings.push(`MANY MESHES · ${meshes} · GUIDANCE`);if(anim===0)info.push('INFO · STATIC ASSET · NO EMBEDDED ANIMATIONS');validation.replaceChildren();if(!warnings.length){const ok=document.createElement('span');ok.className='validation-ok';ok.textContent='PASS · NO BASIC BUDGET WARNINGS';validation.append(ok)}warnings.forEach(text=>{const row=document.createElement('span');row.className='validation-warning';row.textContent=text;validation.append(row)});info.forEach(text=>{const row=document.createElement('span');row.className='inventory-empty';row.textContent=text;validation.append(row)})};
    const restoreHelpers=()=>{tools.querySelectorAll<HTMLButtonElement>('.helpers [data-tool].is-active').forEach(button=>{const tool=button.dataset.tool;if(!tool||tool==='grid')return;root.dispatchEvent(new CustomEvent('corelab:helper',{detail:{tool,enabled:true}}))});const grid=tools.querySelector<HTMLButtonElement>('[data-tool="grid"]');stage?.classList.toggle('inspection-grid',Boolean(grid?.classList.contains('is-active')))};
    root.addEventListener('corelab:telemetry',((event:CustomEvent<Telemetry>)=>{telemetry=event.detail;const tri=Number(telemetry.triangles||0),verts=Number(telemetry.vertices||0),mats=Number(telemetry.materials||0),meshes=Number(telemetry.meshes||0),anim=Number(telemetry.animations||0);if(audit)audit.textContent=`${meshes} meshes · ${mats} materials · ${anim} animations · ${telemetry.size??'—'}`;let level='LIGHT';if(tri>150000||verts>200000||mats>30)level='HEAVY';else if(tri>60000||verts>90000||mats>15)level='MEDIUM';if(performance){performance.textContent=`${level} · ${tri.toLocaleString()} triangles · ${verts.toLocaleString()} vertices`;performance.dataset.level=level.toLowerCase()}validate(telemetry);restoreHelpers();tell('ASSET ANALYZED')})as EventListener);
    root.addEventListener('corelab:inventory',((event:CustomEvent<Inventory>)=>{currentInventory=event.detail;if(!inventory)return;inventory.replaceChildren();event.detail.meshes.forEach((mesh,index)=>{const row=document.createElement('div');row.className='mesh-row';row.innerHTML=`<div><small>MESH ${String(index+1).padStart(2,'0')}</small><b></b><span></span></div><button type="button"></button>`;const name=row.querySelector('b'),materials=row.querySelector('span'),button=row.querySelector('button');if(name)name.textContent=mesh.name;if(materials)materials.textContent=mesh.materials.join(' · ')||'No material';if(button){button.textContent=mesh.visible?'HIDE':'SHOW';button.classList.toggle('is-off',!mesh.visible);button.addEventListener('click',()=>root.dispatchEvent(new CustomEvent('corelab:mesh-visibility',{detail:{id:mesh.id,visible:!mesh.visible}})))}inventory.append(row)});if(!event.detail.meshes.length)inventory.innerHTML='<span class="inventory-empty">NO MESHES FOUND</span>'})as EventListener);tools.querySelector<HTMLButtonElement>('[data-show-all]')?.addEventListener('click',()=>root.dispatchEvent(new CustomEvent('corelab:show-all-meshes')));tools.querySelector<HTMLButtonElement>('[data-hide-all]')?.addEventListener('click',()=>{if(!currentInventory.meshes.length){tell('LOAD A MODEL FIRST');return}currentInventory.meshes.filter(mesh=>mesh.visible).forEach(mesh=>root.dispatchEvent(new CustomEvent('corelab:mesh-visibility',{detail:{id:mesh.id,visible:false}})));tell('ALL MESHES HIDDEN')});
    tools.querySelectorAll<HTMLButtonElement>('[data-tool]').forEach(button=>button.addEventListener('click',async()=>{const tool=button.dataset.tool;if(tool==='copy'){const config=JSON.stringify(getConfig(),null,2);try{await navigator.clipboard.writeText(config);tell('CONFIG COPIED')}catch{tell('COPY BLOCKED BY BROWSER')}return}if(tool==='export'){if(!Object.keys(telemetry).length){tell('LOAD A MODEL FIRST');return}const report=JSON.stringify({coreAssetLab:'0.1.0',validation:validation?.textContent?.trim()||'',...getConfig()},null,2),blob=new Blob([report],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`core-asset-lab-${String(telemetry.file??'report').replace(/\.[^.]+$/,'')}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),0);tell('REPORT EXPORTED');return}if(tool==='refit'){root.dispatchEvent(new CustomEvent('corelab:reset-view'));tell('MODEL CENTERED / REFIT');return}if(tool==='snapshot'){if(!Object.keys(telemetry).length){tell('LOAD A MODEL FIRST');return}root.dispatchEvent(new CustomEvent('corelab:snapshot',{detail:{file:String(telemetry.file??'snapshot')}}));tell('SNAPSHOT REQUESTED');return}button.classList.toggle('is-active');const enabled=button.classList.contains('is-active');if(tool==='grid'){stage?.classList.toggle('inspection-grid',enabled);tell(`GRID ${enabled?'ON':'OFF'}`);return}root.dispatchEvent(new CustomEvent('corelab:helper',{detail:{tool,enabled}}));tell(`${tool?.toUpperCase()} ${enabled?'ON':'OFF'}`)}));
  }
}
